### PR TITLE
Test for proxy to be applied

### PR DESCRIPTION
**Pull request by dangowans**
Not really sure this is the best test as the proxy script will not exist.

### CODE REVIEW

**Comment by dangowans** [comment]
You win Travis.  I give.

**Comment by jgravois** [comment]
i restarted the build. there's a [real error](https://travis-ci.org/Esri/esri-leaflet/builds/417390029#L2732) in your new test.

once you get it sorted out, just tack the commit directly on top of the branch you're already working on for #1122

**Comment by jgravois** [comment]
everything's relative, but "setting up an entire dev environment" only entails:

1. `git clone https://github.com/Esri/esri-leaflet` (or using your UI of choice)
2. `npm install && npm start`

https://github.com/Esri/esri-leaflet#development-instructions

if you're interested in a new challenge, we're happy to answer questions. if not, that's okay too. i will find time to write a test and land #1122 _eventually_.

**Comment by jgravois** [comment]
oh wow.

travis' only problem with your test was that your actual bug fix wasn't available on this branch.

i cherry picked your work and added it to #1122 myself.

**Pull request closed without merging**
