### PR TITLE
Add MultiPolygon support to Query

### PR DESCRIPTION
**Pull request by whyvez**
see: #865

### CODE REVIEW

**Comment by jgravois** [comment]
the error Travis is reporting is coming straight from the [linter](https://travis-ci.org/Esri/esri-leaflet/builds/167186177#L1026).
```bash
/home/travis/build/Esri/esri-leaflet/src/Tasks/Query.js
214:136  error  There should be no spaces inside this paren
```

**Comment by jgravois** [comment]
you've definitely unearthed some working MultiPolygon query support. very cool!
```js
var holeOverCatalina = {
  "type": "MultiPolygon",
  "coordinates": [
    [[[-118.035, 33.625], [-118.892, 33.625], [-118.892, 33.139], [-118.035, 33.139],  [-118.035, 33.625]]],
    [[[-118.135, 33.525], [-118.792, 33.525], [-118.792, 33.239], [-118.135, 33.239], [-118.135, 33.525]]]
  ]
}

L.esri.query({
  url:'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3'
})
  .intersects(holeOverCatalina)
  .run(function (err, res, raw) {
    console.log(res.features.length); // returns 0 features (as it should)
  })
```
1. we'll need to update the warning immediately below to acknowledge that the new geometry type is a valid input
2. we also need to include a new unit test like the one below

```js
var rawMultiPolygon = {
  'type': 'MultiPolygon',
  'coordinates': [
    [[[-97, 39], [-97, 41], [-94, 41], [-94, 39], [-97, 39]]],
    [[[-96, 39.5], [-96, 40.5], [-95, 40.5], [-95, 39.5], [-96, 39.5]]]
  ]
};

it('should query features within a geojson multipolygon geometry', function (done) {
  server.respondWith('GET', featureLayerUrl + 'query?returnGeometry=true&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22rings%22%3A%5B%5B%5B-97%2C39%5D%2C%5B-97%2C41%5D%2C%5B-94%2C41%5D%2C%5B-94%2C39%5D%2C%5B-97%2C39%5D%5D%2C%5B%5B-96%2C39.5%5D%2C%5B-96%2C40.5%5D%2C%5B-95%2C40.5%5D%2C%5B-95%2C39.5%5D%2C%5B-96%2C39.5%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryPolygon&spatialRel=esriSpatialRelContains&f=json', JSON.stringify(sampleQueryResponse));

  task.within(rawMultiPolygon).run(function (error, featureCollection, raw) {
    expect(featureCollection).to.deep.equal(sampleFeatureCollection);
    expect(raw).to.deep.equal(sampleQueryResponse);
    done();
  });

  server.respond();
});
```
if you're not up for laying down the additional changes, i can chuck them in after merging.

**Comment by whyvez** [comment]
@jgravois OK will do. Thanks for the lo down.

**Comment by jgravois** [comment]
awesome. thanks again!

**Pull request merged**
