### PR TITLE
Test time range on features before adding to map

### PR DESCRIPTION
**Pull request by pjbiogit**
Test if feature is within time range before any addLayer call.

### CODE REVIEW

**Comment by jgravois** [comment]
@gavinr whenever you find time to review this, make sure to explore its relationship with https://github.com/Esri/esri-leaflet/pull/1152 

@pjbiogit, what `timeFilterMode` was causing incorrect behavior? for the default (`server`), the client code should be able to safely skip filtering when making new requests.

**Comment by pjbiogit** [comment]
I attempted using both server and client for the `timeFilterMode` and got the same results prior to my changes. Following changes, both modes function the same way.

**Comment by patrickarlt** [comment]
@gavinr this looks pretty good to me. I say we should merge this and cut a new release.

**Comment by gavinr** [comment]
thanks @pjbiogit!

**Pull request merged**
