### PR TITLE
add license to bower.json

### PR DESCRIPTION
**Pull request by anotheredward**

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for this.  my first instinct is that including a license in the `package.json` should be sufficient since bower ultimately just pulls down a git tag.  

is there a specific reason why i might be wrong?

**Comment by anotheredward** [comment]
Hi! Thanks for your reply.

The reason I've put this PR together is to make scraping licenses easier for automated tooling.
When a project has many bower packages it takes a lot of time to look at each one individually and work out what the licenses are.

If a project has a bower.json, does it also always have a package.json with correct license information?

If so, I have seriously misunderstood bower and I apoligise!

**Comment by jgravois** [comment]
thanks for taking the time to clarify.

> If a project has a `bower.json`, does it also always have a `package.json` with correct license information?

there's no guarantee that a package installed via bower will have a `package.json` (which serves as an indication that it has been published to `npm`) but due to npm's popularity, it'd definitely be smart for you to look for such a file in the root of a dependency's directory in order to glean information about the license.

this is kind of *yet another reason* bower is a source of frustration for library authors and why some [rally against it](https://gofore.com/stop-using-bower/).

as far as esri-leaflet goes, we continue to make our plugins available via bower (#700), but we have been intentional about migrating as much duplicitous information as possible **out** of the `bower.json` file as possible.

hope that helps!

**Comment by anotheredward** [comment]
Thanks for your patience.
You've been very clear on where you and the project stand, I will happily close my PR and tweak my searches :).
I'd love if npm were the only way to get packages, but fully support making things available through bower.

**Pull request closed without merging**
