### PR TITLE
Fix problem with fetching AGS layers in polar

### PR DESCRIPTION
**Pull request by scaddenp**
this fix proposed in https://github.com/Leaflet/Leaflet/issues/5617 for correctly located AGS maplayers on polar stereographic projections.

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for this! 

i have my hands full at [UC](http://www.esri.com/about/events/uc) this week, but i'll make time to review your patch fully soon.

**Comment by scaddenp** [comment]
Fixed a bunch of style errors

**Comment by scaddenp** [comment]
The integration is failing tests, but doesnt seem to be anything to do with this fix. As far as we can see, the same failures in FeatureManager are present in the master branch. The changes pass the DynamicMapLayer Tests

**Comment by jgravois** [comment]
no doubt. the errors are from #967.

I'll pull down your branch and verify locally soon.

**Comment by jgravois** [comment]
thanks for your patience. now that i'm back in the office i've reviewed your patch and it looked great!

screenshot 2017-07-17 14 58 23

i DRYed up the logic for the benefit of `L.esri.imageMapLayer` and cherry-picked your commit (bcc9a33) in #975.

thank you *so* much for taking the time to make this contribution! its really a cool one!

**Pull request closed without merging**
