### PR TITLE
fix script url

### PR DESCRIPTION
**Pull request by thinking-aloud**
The script URL was broken and did not work.

### CODE REVIEW

**Comment by jgravois** [comment]
because of this jsdelivr/jsdelivr/issues/5796 'latest' returns the wrong version of our API.  for the time being, it'd probably be best for us to replace with:
```html
<script src="http://cdn.jsdelivr.net/leaflet.esri/1.0.0/esri-leaflet.js"></script>
```
if you're up for laying down another commit in this PR, i'd be happy to merge.

**Comment by patrickarlt** [comment]
@jgravois now that I have managed to eliminate using `latest` from the web samples I think it would be best to just start hardcoding this and changing it every few releases.

**Comment by jgravois** [comment]
agreed.

**Comment by jgravois** [comment]
closed (via 63f735e17aa74c051535a662036c395ab6bec450)

**Pull request closed without merging**
