### PR TITLE
more 1.0.0 constructor refactor sample fixes

### PR DESCRIPTION
**Pull request by jgravois**
i've included some fixes for broken samples and an update to the gruntfile to make sure and incorporate `FeatureLayerService` into the build.

### CODE REVIEW

**Comment by patrickarlt** [comment]
@jgravois Could you add `FeatureLayerService` here too https://github.com/Esri/esri-leaflet/pull/583/files#diff-35b4a816e0441e6a375cd925af50752cR104.

I havn't updated the cluster or heatmap stuff on the docs site. I wanted to settle everything else first and then do those all at once.

**Comment by jgravois** [comment]
i'm happy to do the refactor on the cluster and heatmap plugins.  

i was surprised everything drew fine when i made the changes above after loading a local build of esri-leaflet 1.0.0

**Comment by jgravois** [comment]
i laid down one more commit.  let me know if that's not the addition you were suggesting.

**Comment by patrickarlt** [comment]
@jgravois looks good. I'm going to start making the updates to heatmap cluster and geocoder to go 1.0.0 as well. If you could start tackling everything else that would be good.

**Comment by jgravois** [comment]
I did the geocoder refactor yesterday
Esri/esri-leaflet-geocoder/pull/75

**Pull request merged**
