### PR TITLE
add plugin doc to website

### PR DESCRIPTION
**Pull request by jgravois**
to do:
- [X] layers.heatmapFeatureLayer 
- [X] tasks.geocode 
- [x] tasks.suggest
- [x] tasks.reverseGeocode
- [x] controls.geosearch
- [x] services.geocodeService
- [x] services.gpService
- [x] tasks.gpTask
- [x] tasks.queryRelated

### CODE REVIEW

**Comment by jgravois** [comment]
this will resolve #558

**Comment by patrickarlt** [comment]
@jgravois is this ready to go? I took a quick look through it and it looks good.

**Comment by jgravois** [comment]
yeah.  i haven't figured out how to fix the CSS for the plugin cards yet, but its safe to merge.

probably a good idea too because someone on [geonet](https://geonet.esri.com/thread/164309) was confused as hell yesterday about the state of `master`.

**Comment by jgravois** [comment]
ok.  i vote we merge and push the new site updates into production. i added a placeholder and link to clustered-feature-layer with an explanation that that plugin in particular is still only compatible with leaflet 0.7.3.

**Comment by patrickarlt** [comment]
@jgravois I'm still nervous about releasing 2.0 stable before leaflet 1.0 stable. I'm going to keep this open for now though. You can cut another beta release if you want though.

**Comment by jgravois** [comment]
fair enough.  if all is well with that second featureLayer.remove() fix, i'll cut `beta.6`.  

you are okay with pushing the 2.0.x site to production though, right?

**Comment by patrickarlt** [comment]
@jgravois No i'm really not ok with pushing website updates for the 2.0 since you have to do some convoluted stuff to get Leaflet 1.0 right now and all the samples still aren't working since the clustering plugin hasn't been upgraded.

**Comment by jgravois** [comment]
it would be trivial to redirect people back to the ClusteredFeatureLayer repo to view a live sample of that plugin compatible 0.7.3, but if you really want to hold off, i can live with that.

**Comment by jgravois** [comment]
rebased and updated `L.esri.request()` doc slightly

**Comment by jgravois** [comment]
confirmed today that i could indeed drop in the source from the `leaflet-proj-refactor` branch of [kartena/Proj4Leaflet](http://github.com/kartena/Proj4Leaflet) to get our [tiled map service with custom projection ](http://esri.github.io/esri-leaflet/examples/non-mercator-projection.html) sample up and running with Leaflet 1.0.0-beta1.

**Comment by jgravois** [comment]
the folks from Proj4Leaflet were kind enough to tag a [new release](https://github.com/kartena/Proj4Leaflet/releases/tag/1.0.0-beta.1), so i threw down another commit to add the sample back to the updated site.

thanks @semone!

**Comment by jgravois** [comment]
need to bump leaflet to 1.0.0beta2 and make sure we're still all good.

**Comment by jgravois** [comment]
laid down another commit which:
* bumps us to leaflet1.0.0-beta.2 (all was well with the samples)
* fixes gruntfile to make sure the `img` dir is copied over to the built version of the website
* bumps the gp and geocoder plugin versions (to fix non-working samples)
* fixes a `z-index` bug in the premium content sample

**Comment by patrickarlt** [comment]
@jgravois as per our talk today. Can you make sure the clustering examples are leaflet 0.7.x and esri leaflet 1.0 and add a message to them? Then we can bump the site to 2.x and update the clustering samples with a tagged release.

**Comment by jgravois** [comment]
absolutely.  i looked at it again this afternoon and decided it would be easiest to just merge this PR as is and push to gh-pages.  afterward i can submit a PR directly to the gh-pages branch with raw html for the clustering and heatmap 0.7.x samples.  

sound good?

**Comment by patrickarlt** [comment]
@jgravois looking at this now that you included the projection stuff we need to wait for the next verion 2.0-rc7 before we push this.

**Comment by jgravois** [comment]
i didn't include any of your new stuff, TiledMapLayers with custom projections worked automatically as soon as i bumped the Proj4Leaflet version.

**Comment by patrickarlt** [comment]
@jgravois no 

* stop documenting imageSr and bboxSr in DynamicMapLayer options
* remove correctZoomLevels from TiledMapLayer doc

Are both part of this PR. So we need to wait for the next release.

**Comment by patrickarlt** [comment]
@jgravois wait a sec I just realized this was into master. I can merge this PR but we cant push to GH pages until we are ready to publish a new version.

**Comment by jgravois** [comment]
oh gotcha.  i'd say imageSr and bboxSr should have been pulled from the doc a long time ago (because setting them didn't have any effect anyway), but the second one is definitely something new and pending.

**Comment by patrickarlt** [comment]
@jgravois merging this but we cant push to gh pages until the next verison.

**Pull request merged**
