### PR TITLE
allow passing of transparent option

### PR DESCRIPTION
**Pull request by qbit**
I was pulling in some layers and I noticed I couldn't specify transparent in the options obj..

### CODE REVIEW

**Comment by patrickarlt** [comment]
Could you also add a default value of `true` here? https://github.com/Esri/esri-leaflet/pull/513/files#diff-92a727b8d8cc44ec622b0a0335471d15L5 we cant pass `undefined` to the API.

**Comment by qbit** [comment]
Added. I can squash it if needed as well.

**Comment by patrickarlt** [comment]
I'm far to bad about squashing my commits to ask it of others :smile:

Merging.

**Comment by qbit** [comment]
:+1:

**Pull request merged**
