### PR TITLE
use @esri/arcgis-rest-request [wip]

### PR DESCRIPTION
**Pull request by jgravois**
### to do:
- [X] update rollup to a version that expects a `module` instead of `jsnext:main`
- [X] confirm that this doesn't break any of the live samples
- [ ] get automated tests passing
- [ ] figure out how to polyfill `fetch` _selectively_
- [ ] pass through errors

### CODE REVIEW

**Comment by Biboba** [comment]
Hi @jgravois ,
I was looking at how to get automated tests passing and noticed that they are couple of librairies out there that support the fetch api:
- fetch-mock (used by arcgis-rest-request)
- sinon-stub-promise 
Do you have already have one in mind ?
Thanks

**Comment by jgravois** [comment]
i'm open to anything @Biboba

**Comment by jgravois** [comment]
from @Biboba 

> - **DynamicMapLayer, ImageMapLayer:**
3 tests failing because of a problem popup related:
•	Can’t find a way to do the test when the popup has rendered
•	fetchMock.flush() does not help : promise has resolved does not mean that callback has been executed

> - **DynamicMapLayer, ImageMapLayer, TiledMapSpec:** 
Test "_should propagate events from the service_" failing:
Don't know how to handle spy on requestend because as the event is triggered after the metadata callback has been called, I can’t find a way to « hook » the test: `expect(requestendSpy.callCount).to.be.above(0);`

> - **FindSpec, IdentifyImageSpec, QuerySpec:**
Part of the tests testing for xhr type are commented : should the promise be returned ? So far it is not the case.
`expect(this.request).to.be.an.instanceof(XMLHttpRequest);`

> - **RequestSpec:**
2 tests testing for error failing : failed not managed yet [code]https://github.com/Esri/esri-leaflet/blob/51940752bd3feee6ad53eb146d9cc2ae030d77d6/src/Request.js#L8)

> - [ ] L.esri.FeatureManager test TODO.
@jgravois I wanted to have your opinion so far on the issues above before going ahead as at a first look it seemed trickier for FeatureManager

**Comment by jgravois** [comment]
one **big** blocker to this is https://github.com/Esri/arcgis-rest-js/issues/114

**Comment by jgravois** [comment]
i sincerely appreciate @Biboba's heroic efforts 🙏, but i'm going to put this one to bed.

**Pull request closed without merging**
