### PR TITLE
Fixed #909 for leaflet v.1

### PR DESCRIPTION
**Pull request by nonZero**
(To be merged into a `v1` branch)

### CODE REVIEW

**Comment by jgravois** [comment]
i've published `v1.0.5` on GitHub and npm.  let me know if you have any trouble with it.

**Comment by nonZero** [comment]
Thank you very much for the quick response!  Can you please push a remote `v1` branch for sending pull requests easily?

**Comment by jgravois** [comment]
> Can you please push a remote `v1` branch for sending pull requests easily?

you can create your own new branch locally from a tag anytime you want.

```bash
# fetch branches *and* tags
$ git fetch --all
Fetching upstream
From https://github.com/Esri/esri-leaflet
 * [new tag]         v1.0.5     -> v1.0.5

# use a tag as the base of your new branch
$ git checkout -b legacy-bug-fix v1.0.5 

$ git log -1
commit ee6503ef218fd4bf7320ff5e280bc904613fa18d
Author: john gravois <jgravois@esri.com>
Date:   Wed Apr 26 11:38:55 2017 -0700

    :package: 1.0.5
```
leaflet `v1.x` has been stable for quite some time now.  what exactly is it that is keeping you from upgrading?

**Comment by nonZero** [comment]
We will probably move to leaflet 1.x soon :-)

Regarding the local branch - that's exactly what I did - however: 

    1. I actually had to branch of @4668d9d  which was not tagged and since it wasn't found in any branch, I almost missed it.
    2. github new pull requests are created on

**Comment by jgravois** [comment]
1. you could have branched from 1a3224c80e6102a132f2804e9a80abf947f94225 / [`v1.0.4`](https://github.com/Esri/esri-leaflet/tree/v1.0.4)
2. if you encounter another bug that *needs* to be patched before you upgrade, don't open a PR. just open an issue and share a link to the branch in your own fork. i can fetch/tag from there.

**Pull request closed without merging**
