### PR TITLE
use @terraformer/arcgis to generate GeoJSON from older ArcGIS services

### PR DESCRIPTION
**Pull request by jgravois**
over the years we've refactored the code that turns ArcGIS Geometries into GeoJSON _more than once_ in this library.

1. originally we inlined a subset of the code from Terraformer
2. later @patrickarlt created a new standalone package https://www.npmjs.com/package/@esri/arcgis-to-geojson-utils
3. by that point, @Esri had _quite a few_ packages and repos that served a similar purpose. and people started getting confused about when they should use what. 

ref: 
* https://github.com/Esri/terraformer-arcgis-parser/issues/44
* https://github.com/Esri/geojson-utils/issues/16

it always irked me that we were maintaining (and sometimes failing to maintain) so much nearly identical code. so i came up with the brilliant idea to publish **even more**. 😝 

see: https://xkcd.com/927

to make a long story long, `@terraformer/arcgis` is pretty much a glorified renaming of `@esri/arcgis-to-geojson-utils`.
to make a long story longer, it comes paired with another package for converting between WKT and GeoJSON and another package for using spatial predicates on GeoJSON. Esri Leaflet doesn't have any use for these, but they're [big in Japan](https://www.youtube.com/watch?v=DdWZKb659K0).

https://www.npmjs.com/package/@terraformer/wkt
https://www.npmjs.com/package/@terraformer/spatial

why rewrite them? mostly to make the functionality in the second two [tree shakable](https://en.wikipedia.org/wiki/Tree_shaking) and to put everything back under the familiar 'Terraformer' umbrella.

my hope is that this will help us archive all our old [Esri/Terraformer](https://github.com/Esri?q=terraformer&type=&language=) code and all the other alternative GeoJSON parsing code we wrote along the way.

only time will tell though.

### CODE REVIEW

**Comment by patrickarlt** [comment]
This LGTM!

**Comment by patrickarlt** [comment]
@jgravois I resolved a merge conflict with #1189. @gavinr this can be merged and released.

**Comment by gavinr** [comment]
This was released in v2.4.0: https://github.com/Esri/esri-leaflet/releases/tag/v2.4.0

**Comment by jgravois** [comment]
excellent. thank you!

**Pull request merged**
