### PR TITLE
A solution to issue #647

### PR DESCRIPTION
**Pull request by brianbancroft**
Here are a few lines that will solve this problem completely.

### CODE REVIEW

**Comment by jgravois** [comment]
I have to catch a :plane: home from morocco, but I'll be able to sit down at a computer and take a look at this in a couple days.

thx @brianbancroft!

**Comment by patrickarlt** [comment]
@brianbancroft this solution looks good. it looks like the travis CI tests are failing when trying to lint this.

To keep the code style consistent could you resolve these? https://travis-ci.org/Esri/esri-leaflet/builds/84613490#L159-L161

**Comment by jgravois** [comment]
you can lint the code locally with [`npm run lint`](https://github.com/Esri/esri-leaflet/blob/master/package.json#L90) and run the tests locally with [`npm test`](https://github.com/Esri/esri-leaflet/blob/master/package.json#L92) when you make changes to make sure all is well.

**Comment by brianbancroft** [comment]
Hey gents, thanks for the heads up. I will look into this now!

**Comment by patrickarlt** [comment]
It looks like the Travis CI build randomly disconnected, which happens sometimes for reasons I have been hopelessly trying to debug forever. I restarted the build and it looks good now.

**Comment by jgravois** [comment]
yay! :100: thanks for sticking with it @brianbancroft!

**Comment by brianbancroft** [comment]
No worries guys, 

Thanks for helping me get the foot in the door. I have a lot more beginner-level questions to ask on topics ranging from specifics to "what next". Would pushing them on the main issue page be a good forum?

**Comment by jgravois** [comment]
we're always happy to help if things aren't working as you expect.  that being said, you might attract even more eyes in [gis.se](http://gis.stackexchange.com/questions/ask?tags=esri-leaflet,leaflet) or the [Esri Leaflet Place](https://geonet.esri.com/discussion/create.jspa?sr=pmenu&containerID=1841&containerType=700&tags=esri-leaflet,leaflet) on Geonet if its more of a 'how to' than a suspected bug.

**Comment by patrickarlt** [comment]
@brianbancroft @jgravois @kentcdodds I just want to share some of my thoughts on watching this whole process go down.

First thanks to @jgravois for putting in the time to actually pull this together and document the issue at hand. Ultimately I think everyone learned a whole bunch of stuff not just @brianbancroft. This is a great exercise for maintainers to test their installation and contributing instructions. For example I would have never thought i necessary to need to document or test the dev process against multiple versions of Node. Having a real watch + recompile + dev server solution seems like a real need.

Overall this was pretty fantastic to watch and I'm glad that @brianbancroft learned a whole bunch. I did too so hopefully the next time will be easier for someone.

**Comment by kentcdodds** [comment]
Yay! This is awesome. Glad it went so well.

**Pull request merged**
